#!/usr/bin/env bash

set -u

CONFIG_DIR="/Users/senohebat/.config/sketchybar"
THEME_DIR="$CONFIG_DIR/theme"
PLUGIN_DIR="$CONFIG_DIR/plugins"

# Colors
source "$THEME_DIR/colors.sh"
PADDING=12

sketchybar --add event aerospace_workspace_change

# Setup AeroSpace workspaces
for sid in $(aerospace list-workspaces --all); do
  sketchybar --add item space.$sid left \
    --subscribe space.$sid aerospace_workspace_change mouse.clicked \
    --set space.$sid \
    background.drawing=on \
    background.color=$TRANSPARENT \
    background.corner_radius=8 \
    background.height=26 \
    background.border_width=0 \
    icon.drawing=off \
    label.font="Hack Nerd Font:Bold:14.0" \
    label.padding_left=$PADDING \
    label.padding_right=$PADDING \
    label.color=$WHITE \
    label="$sid" \
    click_script="aerospace workspace $sid" \
    script="$PLUGIN_DIR/aerospace.sh $sid"
done
