#!/usr/bin/env bash

sketchybar \
  --add item memory e \
  --set memory update_freq=20 script="$PLUGIN_DIR/memory.sh" \
  icon="" \
  label.font="Hack Nerd Font:Italic:13.0" \
  icon.color=0x44FFFFFF \
  label.color=0x44FFFFFF
