-- Keymaps for nvim-jdtls
vim.keymap.set("n", "<A-o>", function()
	require("jdtls").organize_imports()
end, { desc = "JDTLS: Organize Imports" })
vim.keymap.set("n", "crv", function()
	require("jdtls").extract_variable()
end, { desc = "JDTLS: Extract Variable" })
vim.keymap.set("v", "crv", function()
	require("jdtls").extract_variable(true)
end, { desc = "JDTLS: Extract Variable (Visual)" })
vim.keymap.set("n", "crc", function()
	require("jdtls").extract_constant()
end, { desc = "JDTLS: Extract Constant" })
vim.keymap.set("v", "crc", function()
	require("jdtls").extract_constant(true)
end, { desc = "JDTLS: Extract Constant (Visual)" })
vim.keymap.set("v", "crm", function()
	require("jdtls").extract_method(true)
end, { desc = "JDTLS: Extract Method (Visual)" })
