theme = "ayu_dark"

[editor]
bufferline="multiple"
line-number = "relative"
color-modes = true
true-color = true
popup-border = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
max-depth = 5

[editor.auto-save]
focus-lost = true

[editor.indent-guides]
character = "╎"
render = true

[editor.statusline]
left = ["mode", "spinner","version-control", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position","position-percentage", "file-encoding"]

[editor.lsp]
# Disable automatically popups of signature parameter help
auto-signature-help = false
# Show LSP messages in the status line
display-messages = true

[keys.normal]
"A-," = "goto_previous_buffer"
"A-." = "goto_next_buffer"
"A-w" = ":buffer-close"
"A-/" = "repeat_last_motion"
A-x = "extend_to_line_bounds"
X = "select_line_above"

[keys.select]
A-x = "extend_to_line_bounds"
X = "select_line_above"

[keys.normal.space]
f = "file_picker_in_current_directory"
F = "file_picker"

[keys.normal.space.g]
f = ":format"

[keys.normal.space.l]
g = ":sh lazygit"

[keys.insert.j]
j = "normal_mode"
