theme = "ayu_dark"

[editor]
bufferline="multiple"
line-number = "relative"
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "╎"
render = true

[editor.statusline]
left = ["mode", "spinner","version-control", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position","position-percentage", "file-encoding"]

[editor.lsp]
# Disable automatically popups of signature parameter help
auto-signature-help = false
# Show LSP messages in the status line
display-messages = true

[keys.normal]
"A-," = "goto_previous_buffer"
"A-." = "goto_next_buffer"
"A-w" = ":buffer-close"
"A-/" = "repeat_last_motion"
A-x = "extend_to_line_bounds"
X = "select_line_above"
#C-f = [":new", ":insert-output lf-pick", ":theme default", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":theme tokyonight_storm"]
#C-f = [":new", ":insert-output lf-pick", ":theme default", "select_all", "split_selection_on_newline", "goto_file", ":buffer-close!", ":theme tokyonight_storm"]
#C-f = [":new", ":insert-output lf-pick", ":theme default", "select_all", "split_selection_on_newline"]
# C-f = [":new",":insert:output yazi",":theme default", "select-all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":theme ayu_dark" ]

[keys.select]
A-x = "extend_to_line_bounds"
X = "select_line_above"

[keys.normal.space]
f = "file_picker_in_current_directory"
F = "file_picker"

[keys.normal.space.g]
f = ":format"

[keys.normal.space.l]
g = ":sh lazygit"

[keys.insert.j]
j = "normal_mode"
