theme = "ayu_dark"

[editor]
line-number = "relative"

[editor.statusline]
left = ["mode", "spinner","version-control", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position","position-percentage", "file-encoding"]

[keys.normal]
C-s = ":w"
C-t = ":sh cmd"
# C-f = [":new",":insert:output yazi",":theme default", "select-all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":theme ayu_dark" ]

[keys.normal.space]
f = "file_picker_in_current_directory"
F = "file_picker"

[keys.normal.space.g]
f = ":format"

[keys.normal.space.l]
g = ":sh lazygit"

[keys.insert.j]
j = "normal_mode"
