#! /bin/sh

exec &> ~/.bspwm_startup_log

# --- Monitor Configuration ---
# MON_LEFT="DP-1-0"
MON_CENTER="DP-1-3"
MON_RIGHT="eDP-2"

xrandr \
    --output "$MON_CENTER" --primary --mode 1920x1080 --rate 165.00 --pos 0x0 \
    --output "$MON_RIGHT"  --mode 2560x1440 --rate 165.00 --scale 0.6x0.6 --pos 1920x0 \

xsetroot -cursor_name left_ptr 

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor "$MON_LEFT"   -d 1 2 
bspc monitor "$MON_CENTER" -d 1 2 3 # Primary monitor gets more desktops
bspc monitor "$MON_RIGHT"  -d 4 5 6

bspc config border_width        2
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false

bspc rule -a Yad state=floating follow=on center=true focus=on
bspc rule -a pavucontrol state=floating follow=on center=true focus=on

bspc rule -a "*\.exe" state=fullscreen

# (NOT USED ANYMORE, CHANGED TO EWW STATUS BAR)
# Polybar 
# Terminate already running bar instances
# polybar-msg cmd quit &> /dev/null # Suppress error if no instances running
# ## Wait for polybar processes to terminate before launching new ones
# while pgrep -u $UID -x polybar >/dev/null; do sleep 0.5; done
#
# # MONITOR=$MON_LEFT polybar --reload main -c ~/.config/polybar/config.ini &
# MONITOR=$MON_CENTER polybar --reload main -c ~/.config/polybar/config.ini &
# MONITOR=$MON_RIGHT polybar --reload main -c ~/.config/polybar/config.ini &

eww -c ~/.config/eww/bar kill > /dev/null 2>&1 # Make sure eww daemon is not running
eww -c ~/.config/eww/bar daemon &
eww -c ~/.config/eww/bar open bar --screen 0 --id primary  &
eww -c ~/.config/eww/bar open bar --screen 1 --id secondary &
pgrep -f "fullscreen_listen.sh" > /dev/null || ~/.config/eww/bar/scripts/fullscreen_listen.sh &

# Start XDG Desktop Portal services
/usr/lib/xdg-desktop-portal-gtk &
/usr/lib/xdg-desktop-portal &

picom --config ~/.config/picom/picom.conf -b # Compositor
# blueman-applet & # Bluetooth
dunst & # Notification System
feh --bg-fill /home/senohebat/Pictures/background.jpg & # Background

# Launch Application at start and send them to specific desktop
# kitty --class RMPC rmpc & sleep 0.5 && bspc node newest -d '^6'
# kitty --class CAVA cava & sleep 0.5 && bspc node newest -d '^6'
flatpak run com.discordapp.Discord & sleep 3 && bspc node newest -d '^5'
youtube-music & sleep 3 && bspc node newest -d '^6'
zen-browser & sleep 3 && bspc node newest -d '^1'
