###################
### Custom Scripts ###
###################

# Rotating Wallpaper
# $changeBackground = swww img $HOME/wallpaper/"$(/usr/bin/ls $HOME/wallpaper | shuf -n 1)" -t any --transition-duration 1.5

# Static Wallpaper
$bgImgPath = "$HOME/wallpapers/daredevil3.jpg"
$changeBackground = swww img $bgImgPath -t any --transition-duration 1

#################
### AUTOSTART ###
#################
# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:
exec-once = blueman-applet # Bluetooth daemon
exec-once = dunst  # Notifications daemon
exec-once = zen-browser
exec-once = hyprpanel
# exec-once = ashell & # Status Bar

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # Forgot what this does
exec-once = swww-daemon && $changeBackground
exec-once = hypridle
exec-once = systemctl --user start hyprpolkitagent # Polkit Authentication Daemon
exec-once = fcitx5 -d
# exec-once = tmux start-server
# exec-once = bongocat -c ~/.config/bongocat/bongocat.conf
