
##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
# windowrule = suppressevent maximize, class:.*
#
# # Fix some dragging issues with XWayland
# windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
#
# # Float the window
# windowrulev2 = float, class:^(BongoCat)$
#
# # Remove borders and maximize visual integration
# windowrulev2 = noborder, class:^(BongoCat)$
# windowrulev2 = noshadow, class:^(BongoCat)$
#
# # Pin it to all workspaces (so it stays visible when you switch)
# windowrulev2 = pin, class:^(BongoCat)$
#
# # Optional: Move it to a specific corner (e.g., bottom right)
# windowrulev2 = move 85% 80%, class:^(BongoCat)$
